### ISSUE TITLE
Link within link tag is not working

### ISSUE THREAD

**Issue by PabloRNC** [HiDeoo/starlight-typedoc#40]
### Describe the bug

I've come across a bug while working with markdown transformation, specifically involving the `@link` tags. It appears that when these tags are converted to markdown, the resulting link is broken and doesn't function properly. This issue is hindering the functionality of the links within the markdown output, making navigation unreliable.

### To Reproduce

1. Create a typescript file with comment referencing another structure

```ts

export interface LinkedInterface {}

/**
* Go to {@link LinkedInterface}
*/
export interface MyInterface {
   linkedInterface: LinkedInterface
}
```

2. Compile that ts file with starlight-typedoc and the markdown convertor and see that the link is broken.

![image](https://github.com/HiDeoo/starlight-typedoc/assets/99443080/3069f703-bfdb-4764-8c61-0775b62f1ae8)

Here is an screenshot about the broken link. As you can see the path to my interface `BanOptions` is `http://localhost:4321/api/chatbot/api/chatbot/interfaces/banoptions` and should be `http://localhost:4321/api/chatbot/interfaces/banoptions`. 

### Expected behavior

The links shouldn't be broken. So  `http://localhost:4321/api/chatbot/api/chatbot/interfaces/banoptions` path should be `http://localhost:4321/api/chatbot/interfaces/banoptions`.

### How often does this bug happen?

Every time

### System Info

- OS: Windows 11
- Opera GX
- `starlight-typedoc`: v0.11.0

**Comment by HiDeoo** [comment]
Thanks for the report.

Would you be able to setup and share a small repository with the example code you shared above leading to that issue?

Having just that exact same code you shared in my case does not generate any invalid links.


https://github.com/HiDeoo/starlight-typedoc/assets/494699/7c680403-59a6-41d5-b348-8bc528aa7f92

**Comment by PabloRNC** [comment]
All right. Here you have. https://github.com/PabloRNC/twitchapi-docs. 

The code is a bit messy.

**Comment by PabloRNC** [comment]
You can see my vercel deploy https://twitchapi-docs.vercel.app/api/chatbot/classes/banmanager/ to test.

**Comment by HiDeoo** [comment]
> All right. Here you have. [PabloRNC/twitchapi-docs](https://github.com/PabloRNC/twitchapi-docs).
> 
> The code is a bit messy.

Yeah, this is why I would prefer a minimal reproduction with the exact same code you shared in your first message as setting up and figuring out the entire code base, finding where the issue even is, etc. will take a lot of time.

**Comment by PabloRNC** [comment]
Yeah. I didn't send it as it was a little bit messy but if you need it.

**Comment by PabloRNC** [comment]
You were able to reproduce the bug?

**Comment by HiDeoo** [comment]
No, I was waiting for a simple repro involving only the code from the original post of the issue. The one you sent contains submodules to an entire code base so I assumed this was definitely not it?

**Comment by PabloRNC** [comment]
The original code from the issue was a simple example about what I was facing. The real code is in that repo and involves all the link tags.

**Comment by CobyPear** [comment]
Hi @HiDeoo. I reported this same (or very similar) issue at #32. I had some time to make a minimal reproduction: https://github.com/CobyPear/starlight-typedoc-broken-links
Let me know if you need any more information. Thanks!

**Comment by HiDeoo** [comment]
@CobyPear Thanks for your repro, super helpful and really appreciated :raised_hands: The issue was easy to spot thanks to the minimal amount of code and your detailed instructions.

You noted 2 issues:

1. "The link in ClassA to ClassAOptions interface does not work"

   This one should be fixed in the version [`0.11.1`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.11.1) that I just released. On top of having a new test for this specific case, I also manually tested this new version locally on your repro and the link works as expected.

2. "The links in ClassB to PackageA are not rendering as links"

   I tested this exact scenario in your reproduction using only TypeDoc with the exact same configuration used in the repro and the generated output contains the same issue. Here is a screenshot of the generated pages by TypeDoc for `ClassA` (left) which includes all expected links and `ClassB` (right) where `ClassA` and `ClassAOptions` are not links.

   <img width="831" alt="typedoc" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/d268bfdf-4bfd-4903-a51c-bd9eb27616a3">

   In this case, not much can be done at the plugin level to fix this issue.

**Comment by CobyPear** [comment]
Thanks much for the quick release!

**Comment by PabloRNC** [comment]
Thanks for the fix.

**Comment by PabloRNC** [comment]
In my case it didn't fix the broken link. It still the same. I have updated to the latest version.
